version: "3"


services:
  myvarnis:
    image: varnish:latest
    volumes:
      - "/home/mike/IdeaProjects/influencer/springboot-varnish/script/default.vcl:/etc/varnish/default.vcl:ro"
    ports:
      - 8090:80

  myspaceapp:
    build: .

