curl localhost:8090/api/greetingnotcached
curl localhost:8090/api/greetingnotcached
curl localhost:8090/api/greetingnotcached
curl localhost:8090/api/greetingnotcached
curl localhost:8090/api/greetingnotcached
curl localhost:8090/api/greetingnotcached
curl localhost:8090/api/greetingnotcached
curl localhost:8090/api/greetingnotcached
curl localhost:8090/api/greetingnotcached
curl localhost:8090/api/greetingnotcached
curl localhost:8090/api/greetingnotcached
curl localhost:8090/api/greetingnotcached